name: Build MacDirtyCow.swift

on: [push]

jobs:
  build:
    name: Build MacDirtyCow.swift
    if: startsWith(github.event.head_commit.message, '[build]')
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: 14.2

    - name: Build
      run: swift build -c release --product MacDirtyCow.swift
